version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongoDb:/data/db
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
  node:
    build: .
    image: modulo:0.7
    command: yarn dev:server
    volumes:
      -  .:/home/node/api
    ports:
      - "3333:3333"
    depends_on:
      - db
      - mongo
